defaults: &defaults
  auth:
    username: "<%= ENV['PROFTPD_API_USERNAME'] %>"
    password: "<%= ENV['PROFTPD_API_PASSWORD'] %>"
  paths:
    ftpasswd: "<%= ENV['PROFTPD_FTPASSWD'] %>"
    users: "<%= ENV['PROFTPD_USERS'] %>"
    groups: "<%= ENV['PROFTPD_GROUPS'] %>"
    home: "<%= ENV['PROFTPD_HOME'] %>"

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
  auth:
    username: test
    password: test
  paths:
    ftpasswd: /test/bin/ftpasswd
    users: /test/etc/users
    groups: /test/etc/groups
    home: /test/home/foo
